name: knowledge_tracing
channels:
  - defaults
dependencies:
  - pip=23.0
  - python=3.9
  - readline=8.2
  - setuptools=65.6
  - sqlite=3.41
  - pip:
      - configargparse==1.7
      - fonttools==4.39
      - ipdb==0.13
      - ipython==8.11
      - json5==0.9
      - jupyterlab==4.0
      - matplotlib==3.7
      - networkx==3.0
      - notebook==7.0
      - numpy==1.22
      - pandas==1.5
      - pillow==9.4
      - psutil==5.9
      - scikit-learn==1.2
      - scipy==1.10
      - seaborn==0.12
      - torch==1.9.0+cu111
      - torchaudio==0.9.0
      - torchvision==0.10.0+cu111
      - tqdm==4.65
